### PR TITLE
add testing pm-143

### PR DESCRIPTION
**Pull request by rawkintrevo**

### CODE REVIEW

**Comment by rawkintrevo** [comment]
preprocessor notebook fails on 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/Downloads/energy_dataset.csv.zip'
```

**Comment by rawkintrevo** [comment]
@fayvor / @wgifford can y'all update these notebooks to a publically available dataset then have the notebook down load the data. Ping when done, I'll merge in your changes, then we'll see if the tests pass

**Comment by rawkintrevo** [comment]
blocked on https://github.com/ibm-granite-community/granite-timeseries-cookbook/issues/18

**Comment by fayvor** [comment]
Commented on #18.

**Comment by rawkintrevo** [comment]
kick starting tests

**Comment by rawkintrevo** [comment]
Thank you @wgifford this works like gang busters now. Merging

**Pull request merged**
