### PR TITLE
Update notebooks

### PR DESCRIPTION
**Pull request by wgifford**
- Update recipes to take into account passing future values for exogenous use cases
- Rerun/cleanup recipes

### CODE REVIEW

**Comment by bjhargrave** [comment]
@wgifford I ran the pre-commit hooks to clean the output from the notebooks.

**Comment by wgifford** [comment]
@bjhargrave For time series we generally do not want to remove the outputs of all the cells. This will remove the plots -- and if these are removed, the utility of the notebook is greatly diminished.

**Comment by bjhargrave** [comment]
Aren't the plots generated by running the notebook? The plots images are very large and make git diffs impossible to read. GitHub won't render them.

**Comment by wgifford** [comment]
We frequently use these recipes to show how things work and the quality of the output -- running them takes 10s of minutes. The outcome of previous discussions on this was to keep the plots.

**Comment by bjhargrave** [comment]
Ok. Buried in the large git diff for recipes/Time_Series/Few-shot_Finetuning_and_Evaluation.ipynb is:

```diff
-    "    \"ibm-granite/granite-timeseries-ttm-r2\",  # Name of the model on HuggingFace.\n",
+    "    \"ibm-granite/granite-timeseries-ttm-r1\",  # Name of the model on HuggingFace.\n",
```

Was it intended to change from r2 back to r1?

**Comment by wgifford** [comment]
> Ok. Buried in the large git diff for recipes/Time_Series/Few-shot_Finetuning_and_Evaluation.ipynb is:
> 
> ```diff
> -    "    \"ibm-granite/granite-timeseries-ttm-r2\",  # Name of the model on HuggingFace.\n",
> +    "    \"ibm-granite/granite-timeseries-ttm-r1\",  # Name of the model on HuggingFace.\n",
> ```
> 
> Was it intended to change from r2 back to r1?

Yes. r1 results were better for the chosen examples.

**Pull request merged**
