### PR TITLE
Recipe/86: time series energy demand zero-shot

### PR DESCRIPTION
**Pull request by fayvor**
[pm/#86](https://github.com/ibm-granite-community/pm/issues/86) Add zero-shot recipe for predicting energy demand time series.
- Install library from branch (to be updated)
- Download and prepare the data
- Construct a Preprocessor
- Configure the model
- Create and execute forecasting pipeline
- Plot the results

### CODE REVIEW

**Comment by fayvor** [comment]
See the [issue](https://github.com/ibm-granite-community/pm/issues/86#issuecomment-2318464652) for a couple remaining to do's.

**Comment by fayvor** [comment]
Remaining to do:
1. Move the plotting function to tsfm-public
2. Pin the tsfm-public version for pip install

**Comment by wgifford** [comment]
A few comments:
- We can remove a few imports: `prepare_data_splits` and `TimeSeriesPreprocessor`
- Remove comments "# tsp.num_input_channels", " # prediction_channel_indices=tsp.prediction_channel_indices," when loading model
- Do we still want the link to the cookbook-dev version?

@fayvor If you want to discuss the plotting in tsfm-public let me know.

**Comment by wgifford** [comment]
Please change the pip install to:
```! pip install "tsfm_public[notebooks] @ git+https://github.com/ibm-granite/granite-tsfm.git@v0.2.8" -U```

**Comment by fayvor** [comment]
The final change, to replace plot_predictions() with tsfm_public.toolkit.visualization.plot_predictions, is waiting on [this PR in granite-tsfm](https://github.com/ibm-granite/granite-tsfm/pull/126).

**Comment by fayvor** [comment]
This now uses `plot_predictions()` from `granite-tsfm`, but the `pip install` points at `main`. Once we have a version of `granite-tsfm` that contains the new code, we can pin this recipe to that version.

**Comment by fayvor** [comment]
@wgifford @adampingel this is pinned now, so we should be able to merge. Please give it a look.

**Review by adampingel — APPROVED** [review]

**Pull request merged**
